import type { AskLafloPageKnowledge } from './types';

const page = (
  id: string,
  name: string,
  description: string,
  routes: string[],
  permission: string | undefined,
  tabs: string[],
  actions: string[],
  prompts: string[],
  workflows: string[] = [],
  commonErrors: string[] = [],
): AskLafloPageKnowledge => ({ id, name, description, routes, permission, tabs, actions, prompts, workflows, commonErrors });

export const askLafloKnowledgeMap: AskLafloPageKnowledge[] = [
  page('dashboard', 'Dashboard', 'A hotel-wide summary of today’s workload, guest activity, rooms, and priorities.', ['/', '/dashboard'], 'dashboard', [], ['navigate.toOperationsCenter'], ['What needs attention today?', 'Which area should I review first?', 'Explain today’s dashboard.']),
  page('operations-center', 'Operations Center', 'A live operational workspace for priorities, advisories, department pressure, and recent hotel activity.', ['/operations-center'], 'bookings', ['overview', 'tasks', 'advisories', 'activity'], ['navigate.toTasksAndAdvisories', 'navigate.toOperationalIntelligence'], ['What needs attention today?', 'Which department is under pressure?', 'What should I do first?', 'Show me open actions.']),
  page('tasks-advisories', 'Tasks & Advisories', 'Review operational advisories, turn supported advisories into tasks, assign work, and track outcomes.', ['/operations/tasks-advisories'], 'bookings', ['all', 'critical', 'assigned-to-me', 'resolved'], ['task.createFromAdvisory', 'task.assignOwner', 'task.dismissAdvisory'], ['Help me create a task.', 'Which advisories need owners?', 'What is overdue?', 'Explain this advisory.'], ['create-task-from-advisory', 'assign-advisory-owner']),
  page('hotel-insights', 'Hotel Insights', 'Brings together hotel information, briefings, evidence, saved prompts, and recommendations used by Ask LaFlo.', ['/hotel-insights', '/operations/hotel-brain-console', '/ai/hotel-brain'], 'bookings', ['overview', 'information', 'recommendations', 'saved-prompts', 'activity'], ['navigate.toRecommendations'], ['Give me today’s hotel briefing.', 'What information can you access?', 'Show recommendations to review.', 'Explain the latest insight.']),
  page('recommendations', 'AI Recommendations', 'Review AI-generated recommendations and decide whether to approve, reject, expire, assign, or create a task.', ['/operations/ai-governance', '/ai-recommendations', '/ai-governance'], 'bookings', ['pending', 'approved', 'rejected', 'task-created', 'expired'], ['recommendation.approve', 'recommendation.reject', 'recommendation.expire', 'recommendation.createTask'], ['What should I approve first?', 'Explain this recommendation.', 'Help me reject this safely.', 'Create a task from this recommendation.'], ['review-recommendation', 'approve-recommendation', 'reject-recommendation']),
  page('enterprise-search', 'Enterprise Search', 'Search authorised hotel records while hiding technical noise unless system or audit results are requested.', ['/operations/enterprise-search', '/operations-center/search'], 'bookings', ['all', 'operations', 'guests', 'system'], ['search.runEnterpriseSearch'], ['What can I find here?', 'Show me how to search.', 'Why are there no results?', 'Clear my search filters.'], ['use-enterprise-search']),
  page('weather', 'Weather & Forecast', 'Shows current conditions, forecast, hotel impact, and weather-related operational actions.', ['/operations/operational-intelligence/weather-forecast', '/weather-forecast', '/operational-intelligence/weather'], 'bookings', ['overview', 'forecast', 'impact', 'actions'], ['weather.refreshForecast'], ['Will weather affect operations today?', 'What should we prepare for?', 'Explain demand impact.', 'Create a weather-related advisory task.'], ['review-weather-impact']),
  page('operational-intelligence', 'Operational Intelligence', 'Combines hotel signals to explain operating posture, department pressure, risks, and recommended actions.', ['/operational-intelligence', '/operations/operational-intelligence'], 'bookings', ['overview', 'weather-impact', 'demand-revenue', 'guest-flow', 'department-pressure', 'risk-signals', 'recommended-actions'], ['navigate.toTasksAndAdvisories', 'navigate.toSecurityCenter', 'navigate.toIncidentCenter'], ['What needs attention across operations?', 'Which department needs attention?', 'Explain the operating posture.', 'What should we do first?']),
  page('market-intelligence', 'Market Intelligence', 'Explains authorised market indicators, competitor coverage, and demand signals.', ['/operations/operational-intelligence/market-intelligence', '/market-intelligence'], 'bookings', ['overview', 'coverage', 'signals'], ['navigate.toRevenueGuidance'], ['Explain the market indicators.', 'Show market coverage.', 'What does this demand signal mean?', 'What should Revenue review?']),
  page('revenue-guidance', 'Revenue Guidance', 'Shows demand direction, pricing opportunity, evidence, and supported pricing-task actions.', ['/operations/operational-intelligence/revenue-guidance', '/revenue-guidance'], 'financials', ['overview', 'calendar', 'guidance', 'evidence'], ['revenue.createPricingTask'], ['Explain this pricing recommendation.', 'Create a pricing task.', 'What does demand softening mean?', 'Show market coverage.'], ['create-pricing-task']),
  page('security-center', 'Security Center', 'A single workspace for CCTV, access activity, visitors, and security alerts.', ['/security-center'], 'security_center', ['overview', 'cctv', 'access-logs', 'visitors', 'alerts'], ['alert.acknowledge', 'navigate.toIntegrationManager'], ['Which alerts need attention?', 'Which cameras are offline?', 'Help me acknowledge an alert.', 'Show me security risks.'], ['acknowledge-security-alert', 'connect-cctv-provider'], ['A provider may be disconnected or not configured.']),
  page('incident-center', 'Incident Center', 'Review, assign, investigate, resolve, and close operational incidents in one workspace.', ['/incidents'], 'incident_management', ['overview', 'active', 'critical', 'assigned-to-me', 'resolved', 'closed'], ['incident.assign', 'incident.resolve', 'incident.close'], ['Show active incidents.', 'Help me resolve an incident.', 'Which incidents are critical?', 'What is assigned to me?'], ['resolve-incident']),
  page('smart-building', 'Smart Building', 'Monitor building devices, doors, sensors, alerts, and facilities health.', ['/operations/smart-building', '/smart-building'], 'smart_building', ['overview', 'doors', 'sensors', 'devices', 'energy', 'hvac', 'assets'], ['navigate.toIntegrationManager', 'task.createFromAdvisory'], ['Which devices are offline?', 'Show held-open doors.', 'Explain this sensor alert.', 'Help me create a maintenance task.']),
  page('integration-manager', 'Integration Manager', 'Configure supported providers, add required connection details, and test live connections.', ['/settings?tab=integrations'], 'settings', ['providers', 'connected', 'available'], ['integration.configureProvider', 'integration.testConnection'], ['Help me connect CCTV.', 'What credentials are required?', 'Test this connection.', 'Why is this provider unavailable?'], ['connect-cctv-provider', 'test-integration-connection'], ['Future integrations are labelled unavailable and cannot pretend to connect.']),
  page('rooms', 'Rooms', 'Manage room inventory, readiness, status, and room types.', ['/rooms'], 'rooms', ['rooms', 'room-types'], ['room.manageTypes'], ['How do I add a room type?', 'Show rooms that are not ready.', 'Explain room status.', 'Why can’t I edit this room?'], ['manage-room-type']),
  page('reservations', 'Reservations', 'Create and manage stays, arrivals, departures, and booking details.', ['/reservations', '/bookings'], 'bookings', ['all', 'arrivals', 'departures'], ['booking.create'], ['Walk me through creating a booking.', 'Show today’s arrivals.', 'Explain this booking status.', 'What information is required?'], ['create-booking']),
  page('guests', 'Guests', 'View authorised guest profiles, stay history, preferences, and service information.', ['/guests'], 'guests', [], [], ['Explain the guest profile.', 'How do I find a guest?', 'What information can I see?', 'Why is information restricted?']),
  page('housekeeping', 'Housekeeping', 'Prioritise room cleaning, inspections, readiness, and housekeeping workload.', ['/housekeeping'], 'housekeeping', ['overview', 'rooms', 'priority'], [], ['What should Housekeeping do now?', 'Which rooms need attention?', 'Explain room readiness.', 'What is the priority order?']),
  page('inventory', 'Inventory', 'Track hotel stock, low-stock warnings, suppliers, and inventory movements.', ['/inventory'], 'inventory', [], [], ['Which items are low?', 'Explain this stock warning.', 'How do I update inventory?', 'What needs ordering?']),
  page('calendar', 'Calendar', 'Review hotel events, operational schedules, and time-based work.', ['/calendar'], 'calendar', [], [], ['What is happening today?', 'How do I add an event?', 'Show upcoming work.', 'Explain this calendar item.']),
  page('financials', 'Financials', 'Review authorised revenue, balances, transactions, and financial performance.', ['/financials'], 'financials', [], [], ['Explain these figures.', 'What needs attention?', 'Why is this amount different?', 'Which records can I export?']),
  page('reviews', 'Reviews', 'Monitor guest feedback, ratings, sentiment, and follow-up work.', ['/reviews'], 'reviews', [], [], ['Which reviews need follow-up?', 'Explain the sentiment.', 'How should we respond?', 'Show recent negative feedback.']),
  page('concierge', 'Concierge', 'Manage guest requests, priorities, ownership, and service outcomes.', ['/concierge'], 'concierge', [], [], ['Which requests are urgent?', 'How do I assign a request?', 'What is overdue?', 'Explain this request.']),
  page('messages', 'Messages', 'Handle guest, team, and support conversations.', ['/messages'], 'messages', [], [], ['How do Messages work?', 'Show unread conversations.', 'How do I contact support?', 'Explain this conversation.']),
  page('calls', 'Calls', 'Manage supported hotel calling workflows and call activity.', ['/calls'], 'messages', [], [], ['How do calls work?', 'Why is calling unavailable?', 'Show recent call activity.', 'What do these controls do?']),
  page('users', 'User Management', 'Manage team members, roles, and module permissions.', ['/users'], 'users', ['users', 'roles'], [], ['How do I add a user?', 'Explain roles and permissions.', 'Why can’t this user access a page?', 'Who can manage access?']),
  page('settings', 'Settings', 'Configure hotel, account, notification, appearance, integration, and access settings.', ['/settings'], 'settings', ['profile', 'hotel', 'notifications', 'appearance', 'integrations', 'audit-trail', 'access-requests'], ['navigate.toIntegrationManager'], ['What can I configure here?', 'Show me integrations.', 'How do I change notifications?', 'Why is a setting restricted?']),
  page('appearance', 'Appearance', 'Choose and save the visual theme and background used in LaFlo.', ['/settings?tab=appearance'], 'settings', ['theme', 'background'], [], ['How do I change the theme?', 'Show me appearance options.', 'Why did my theme not save?', 'Reset my appearance.'], ['change-appearance']),
  page('notifications', 'Notifications', 'Choose which hotel notifications are enabled and how they are delivered.', ['/settings?tab=notifications'], 'settings', ['preferences', 'delivery'], [], ['How do I change notifications?', 'Which alerts are enabled?', 'Why is a notification restricted?', 'How is delivery configured?']),
  page('audit-trail', 'Audit Trail', 'Review recorded workspace activity and audit-retention settings.', ['/settings?tab=audit-trail'], 'settings', ['activity', 'retention'], [], ['What does the audit trail show?', 'How do I filter activity?', 'Is this production history?', 'How do I export it?']),
  page('access-requests', 'Access Requests', 'Admin-only review of requests for workspace access.', ['/settings?tab=access-requests'], 'users', ['pending', 'reviewed'], [], ['Show pending access requests.', 'How do I review a request?', 'Why is this restricted?', 'Who can approve access?'], ['review-access-requests']),
];

const normalizeRoute = (route: string) => route.replace(/\/$/, '') || '/';

export function getAskLafloPageKnowledge(route: string): AskLafloPageKnowledge {
  const [pathname] = route.split('?');
  const exact = askLafloKnowledgeMap.find((item) => item.routes.includes(route));
  if (exact) return exact;
  const match = askLafloKnowledgeMap
    .flatMap((item) => item.routes.map((candidate) => ({ item, candidate })))
    .filter(({ candidate }) => {
      const [candidatePath] = candidate.split('?');
      return normalizeRoute(pathname) === normalizeRoute(candidatePath) || (candidatePath !== '/' && pathname.startsWith(`${normalizeRoute(candidatePath)}/`));
    })
    .sort((a, b) => b.candidate.length - a.candidate.length)[0];
  return match?.item || askLafloKnowledgeMap[0];
}
