import type { AskLafloWalkthrough } from './types';

const step = (title: string, instruction: string, route: string, target: string | undefined, actionRequired: string, completionCondition: string) => ({ title, instruction, route, target, actionRequired, completionCondition });

export const askLafloWalkthroughs: AskLafloWalkthrough[] = [
  { id: 'create-task-from-advisory', title: 'Create a task from an advisory', purpose: 'Turn an operational advisory into tracked work.', permission: 'bookings', aliases: ['create a task', 'task from advisory'], steps: [step('Open Tasks & Advisories', 'Go to Tasks & Advisories.', '/operations/tasks-advisories', 'Tasks & Advisories workspace', 'Open the page.', 'Tasks & Advisories is visible.'), step('Select an advisory', 'Choose the advisory that needs action.', '/operations/tasks-advisories', 'Advisory row', 'Open its details.', 'The advisory details are open.'), step('Start task creation', 'Choose Create task.', '/operations/tasks-advisories', 'Create task button', 'Open the prefilled drawer.', 'The task drawer is visible.'), step('Review and save', 'Check the title, reason, priority, and department, then save.', '/operations/tasks-advisories', 'Create task confirmation', 'Confirm task creation.', 'A linked task ID and Task created status appear.')] },
  { id: 'assign-advisory-owner', title: 'Assign an advisory owner', purpose: 'Give an operational advisory a clear owner.', permission: 'bookings', aliases: ['assign advisory', 'assign owner'], steps: [step('Open the advisory', 'Open Tasks & Advisories and select the advisory.', '/operations/tasks-advisories', 'Advisory row', 'Open details.', 'Advisory details are visible.'), step('Choose Assign', 'Choose Assign owner.', '/operations/tasks-advisories', 'Assign owner button', 'Open assignment.', 'The assignment modal opens or a clear unavailable message appears.'), step('Save the owner', 'Select the authorised owner or team and save.', '/operations/tasks-advisories', 'Save assignment', 'Confirm assignment.', 'The record shows the saved owner, or remains unchanged when unavailable.')] },
  { id: 'review-recommendation', title: 'Review an AI recommendation', purpose: 'Check evidence before deciding what happens next.', permission: 'bookings', aliases: ['review recommendation', 'review ai recommendation'], steps: [step('Open AI Recommendations', 'Open the Pending queue.', '/operations/ai-governance?status=PENDING', 'Pending tab', 'Open the queue.', 'Pending recommendations are visible.'), step('Open details', 'Select a recommendation and choose View details.', '/operations/ai-governance?status=PENDING', 'View details button', 'Review the detail panel.', 'Evidence, source, comments, and audit trail are visible.'), step('Choose an outcome', 'Approve, Reject, Expire, assign an owner, or create a task where supported.', '/operations/ai-governance?status=PENDING', 'Recommendation actions', 'Choose an authorised action.', 'The recommendation moves to the matching status.')] },
  { id: 'approve-recommendation', title: 'Approve a recommendation', purpose: 'Approve a reviewed recommendation safely.', permission: 'bookings', aliases: ['approve recommendation'], steps: [step('Review evidence', 'Open the recommendation and check its source and details.', '/operations/ai-governance?status=PENDING', 'View details', 'Review evidence.', 'The evidence panel has been reviewed.'), step('Approve', 'Choose Approve and confirm.', '/operations/ai-governance?status=PENDING', 'Approve button', 'Confirm approval.', 'The item appears under Approved.')] },
  { id: 'reject-recommendation', title: 'Reject a recommendation', purpose: 'Reject a recommendation with a clear reason.', permission: 'bookings', aliases: ['reject recommendation'], steps: [step('Open recommendation', 'Open the Pending recommendation.', '/operations/ai-governance?status=PENDING', 'Recommendation row', 'Review details.', 'Details are visible.'), step('Reject safely', 'Choose Reject, add the reason where requested, and confirm.', '/operations/ai-governance?status=PENDING', 'Reject button', 'Confirm rejection.', 'The item appears under Rejected with its audit activity.')] },
  { id: 'acknowledge-security-alert', title: 'Acknowledge a security alert', purpose: 'Record that an authorised user has taken ownership of an alert.', permission: 'security_center', aliases: ['acknowledge alert', 'security alert'], steps: [step('Open Alerts', 'Open Security Center and choose Alerts.', '/security-center?tab=alerts', 'Alerts tab', 'Open the alert list.', 'Alerts are visible.'), step('Review the alert', 'Open the alert details and check its evidence.', '/security-center?tab=alerts', 'Alert row', 'Review details.', 'Alert details are visible.'), step('Acknowledge', 'Choose Acknowledge and confirm.', '/security-center?tab=alerts', 'Acknowledge button', 'Confirm acknowledgement.', 'The alert status and active counts update.')] },
  { id: 'resolve-incident', title: 'Resolve an incident', purpose: 'Record the operational outcome of an active incident.', permission: 'incident_management', aliases: ['resolve incident', 'resolve an incident', 'close an incident'], steps: [step('Open active incidents', 'Open Incident Center and choose Active.', '/incidents?tab=active', 'Active tab', 'Open the list.', 'Active incidents are visible.'), step('Review the incident', 'Open the incident and confirm the response is complete.', '/incidents?tab=active', 'Incident row', 'Review the record.', 'Incident details are visible.'), step('Resolve', 'Choose Resolve and confirm.', '/incidents?tab=active', 'Resolve button', 'Confirm resolution.', 'The incident moves to Resolved and counts update.')] },
  { id: 'connect-cctv-provider', title: 'Connect a CCTV provider', purpose: 'Configure a supported CCTV provider with real connection details.', permission: 'settings', aliases: ['connect cctv', 'configure cctv', 'add camera'], steps: [step('Open Integration Manager', 'Open Settings → Integrations.', '/settings?tab=integrations', 'Integrations tab', 'Open the provider catalogue.', 'Integration Manager is visible.'), step('Choose CCTV', 'Filter to CCTV and select a supported provider.', '/settings?tab=integrations', 'CCTV provider card', 'Open setup.', 'The provider setup drawer opens.'), step('Enter connection details', 'Enter the host and credentials requested by that provider.', '/settings?tab=integrations', 'Provider credentials', 'Save configuration.', 'The provider is configured without exposing saved secrets.'), step('Test connection', 'Choose Test connection and wait for success, failure, or unavailable.', '/settings?tab=integrations', 'Test connection button', 'Run the test.', 'A real connection outcome is shown.')] },
  { id: 'test-integration-connection', title: 'Test an integration connection', purpose: 'Verify a configured provider can be reached.', permission: 'settings', aliases: ['test connection', 'test integration'], steps: [step('Open configured providers', 'Open Integration Manager and select the configured provider.', '/settings?tab=integrations', 'Configured provider', 'Open provider details.', 'Provider details are visible.'), step('Run the test', 'Choose Test connection.', '/settings?tab=integrations', 'Test connection button', 'Wait for the test.', 'Loading ends with success, failure, or unavailable.')] },
  { id: 'review-weather-impact', title: 'Review weather impact', purpose: 'Understand how the forecast affects hotel operations.', permission: 'bookings', aliases: ['weather impact', 'prepare for weather'], steps: [step('Open Weather & Forecast', 'Open the weather workspace.', '/operations/operational-intelligence/weather-forecast', 'Weather overview', 'Open the page.', 'Current conditions and update time are visible.'), step('Review impact', 'Check operational impact and preparation advice.', '/operations/operational-intelligence/weather-forecast', 'Impact section', 'Review the signals.', 'Weather-driven risks and actions are visible or marked unavailable.')] },
  { id: 'create-pricing-task', title: 'Create a pricing task', purpose: 'Turn supported revenue guidance into tracked work.', permission: 'financials', aliases: ['create pricing task', 'pricing task'], steps: [step('Open Revenue Guidance', 'Open the revenue workspace.', '/operations/operational-intelligence/revenue-guidance', 'Revenue Guidance', 'Open the page.', 'Demand and pricing guidance are visible.'), step('Select guidance', 'Choose a supported pricing recommendation.', '/operations/operational-intelligence/revenue-guidance', 'Pricing recommendation', 'Open details.', 'Recommendation evidence is visible.'), step('Create task', 'Choose Create task, review the prefilled details, and save.', '/operations/operational-intelligence/revenue-guidance', 'Create task button', 'Confirm task creation.', 'A linked task appears or a clear unavailable message is shown.')] },
  { id: 'use-enterprise-search', title: 'Use Enterprise Search', purpose: 'Find authorised hotel records without technical noise.', permission: 'bookings', aliases: ['enterprise search', 'search hotel records'], steps: [step('Open Enterprise Search', 'Open the search workspace.', '/operations/enterprise-search', 'Search input', 'Open the page.', 'The search input is visible.'), step('Enter a hotel question', 'Use a guest, room, task, incident, or operational phrase.', '/operations/enterprise-search', 'Search input', 'Run Search.', 'Filtered results or a no-results state appears.'), step('Refine safely', 'Use category and status filters. Choose System or Audit only when technical records are needed.', '/operations/enterprise-search', 'Search filters', 'Adjust filters.', 'Results and counts update.')] },
  { id: 'change-appearance', title: 'Change appearance', purpose: 'Choose and save a LaFlo theme and background.', permission: 'settings', aliases: ['change appearance', 'change theme'], steps: [step('Open Appearance', 'Open Settings → Appearance.', '/settings?tab=appearance', 'Appearance tab', 'Open the page.', 'Theme options are visible.'), step('Choose and save', 'Select the theme and background, then choose Save appearance.', '/settings?tab=appearance', 'Save appearance button', 'Save changes.', 'The page confirms the appearance is saved.')] },
  { id: 'review-access-requests', title: 'Review access requests', purpose: 'Review workspace access requests as an administrator.', permission: 'users', aliases: ['review access requests', 'access request'], steps: [step('Open Access Requests', 'Open Settings → Access Requests.', '/settings?tab=access-requests', 'Access Requests tab', 'Open the page.', 'Requests or a clear empty state are visible.'), step('Review the request', 'Open the request and check the requested role and modules.', '/settings?tab=access-requests', 'Access request row', 'Review details.', 'The authorised review actions are visible.')] },
  { id: 'manage-room-type', title: 'Add or edit a room type', purpose: 'Maintain room-type information used by room inventory.', permission: 'rooms', aliases: ['add room type', 'edit room type'], steps: [step('Open Rooms', 'Open Rooms and choose Room types.', '/rooms', 'Room types tab', 'Open room types.', 'Room types are visible.'), step('Add or edit', 'Choose Add room type or open an existing type.', '/rooms', 'Add room type button', 'Open the form.', 'The room-type form is visible.'), step('Save', 'Enter the required information and save.', '/rooms', 'Save room type button', 'Confirm save.', 'The type appears in the list or a clear unavailable message appears.')] },
  { id: 'create-booking', title: 'Create a booking', purpose: 'Create a reservation with the required guest and stay details.', permission: 'bookings', aliases: ['create booking', 'new booking'], steps: [step('Open Reservations', 'Open Reservations.', '/reservations', 'Reservations workspace', 'Open the page.', 'Reservations are visible.'), step('Start a booking', 'Choose New booking.', '/reservations', 'New booking button', 'Open booking creation.', 'The booking form or drawer is visible.'), step('Enter and save details', 'Complete guest, dates, room/rate, and required contact details, then save.', '/reservations', 'Save booking button', 'Confirm creation.', 'The new booking appears with its reference.')] },
];

export function findAskLafloWalkthrough(text: string): AskLafloWalkthrough | null {
  const normalized = text.toLowerCase();
  return askLafloWalkthroughs.find((walkthrough) => walkthrough.aliases.some((alias) => normalized.includes(alias))) || null;
}
