export const dashboardDemoData = {
  summary: {
    todayArrivals: 18,
    todayDepartures: 11,
    currentOccupancy: 86,
    totalRooms: 144,
    occupiedRooms: 124,
    availableRooms: 20,
    outOfServiceRooms: 3,
    inHouseGuests: 186,
    todayRevenue: 18420,
    monthRevenue: 286300,
  },
  housekeeping: {
    clean: 102,
    dirty: 17,
    inspection: 9,
    outOfService: 3,
    priorityRooms: [],
  },
  maintenance: {
    workOrders: { open: 8 },
    faults: { urgent: 2 },
    repairs: { inProgress: 4 },
    preventiveMaintenance: { overdue: 1 },
    assets: { dueInspection: 3 },
    completed: { today: 7 },
    recentActivity: [],
  },
  incidents: {
    active: 4,
    critical: 1,
    resolved: 6,
    closed: 18,
    total: 28,
    averageResolutionMinutes: 42,
    byDepartment: [],
    bySourceModule: [],
  },
  security: {
    cctv: { total: 24, online: 22, offline: 2 },
    accessEvents: { today: 312 },
    visitors: { onsite: 8 },
    alerts: { open: 3 },
    recentActivity: [],
  },
  smart: {
    cameras: { online: 22, offline: 2 },
    doors: { locked: 31, open: 2 },
    accessEvents: { today: 312 },
    motionAlerts: { active: 1 },
    temperatureSensors: { normal: 38, warning: 2 },
    waterLeakSensors: { alerts: 0 },
    panicButtons: { active: 0 },
    health: { activeAlerts: 3, onlineDevices: 93, totalDevices: 98 },
  },
  revenue: [
    { period: 'Dec', value: 168000 },
    { period: 'Jan', value: 184000 },
    { period: 'Feb', value: 232000 },
    { period: 'Mar', value: 286300 },
    { period: 'Apr', value: 248000 },
    { period: 'May', value: 291000 },
  ],
  bookingSources: [
    { name: 'Direct booking', value: 61, color: '#2fbf9f' },
    { name: 'Booking.com', value: 12, color: '#75d8ca' },
    { name: 'Agoda', value: 11, color: '#9db9f5' },
    { name: 'Airbnb', value: 9, color: '#f8cf69' },
    { name: 'Hotels.com', value: 5, color: '#f39a96' },
    { name: 'Others', value: 2, color: '#cbd5e1' },
  ],
  reviewCategories: [
    { name: 'Facilities', score: 4.4 },
    { name: 'Cleanliness', score: 4.7 },
    { name: 'Service', score: 4.6 },
    { name: 'Comfort', score: 4.8 },
    { name: 'Location', score: 4.5 },
  ],
  tasks: [
    { id: 'task-1', title: 'Prioritise arrival rooms', category: 'Housekeeping', due: '10:30', priority: 'High', owner: 'Floor team' },
    { id: 'task-2', title: 'Resolve camera outage', category: 'Security', due: '11:00', priority: 'High', owner: 'Security' },
    { id: 'task-3', title: 'Inspect HVAC fault', category: 'Maintenance', due: '13:30', priority: 'Medium', owner: 'Engineering' },
    { id: 'task-4', title: 'Follow up guest requests', category: 'Front desk', due: '15:00', priority: 'Medium', owner: 'Reception' },
  ],
  bookings: [
    { id: 'LF-00108', guest: 'Amara Cooper', room: '101', roomType: 'Deluxe', checkIn: 'Today, 13:00', checkOut: '22 Jun', nights: 3, total: 945, status: 'Checked-in', source: 'Direct booking' },
    { id: 'LF-00109', guest: 'Catherine Lopp', room: '202', roomType: 'Standard', checkIn: 'Today, 14:00', checkOut: '21 Jun', nights: 2, total: 568, status: 'Confirmed', source: 'Booking.com' },
    { id: 'LF-00110', guest: 'Emily Johnson', room: '302', roomType: 'Suite', checkIn: 'Today, 15:30', checkOut: '22 Jun', nights: 4, total: 1428, status: 'Pending', source: 'Agoda' },
    { id: 'LF-00111', guest: 'Daniel Brooks', room: '107', roomType: 'Deluxe', checkIn: 'Tomorrow', checkOut: '22 Jun', nights: 2, total: 630, status: 'Confirmed', source: 'Direct booking' },
    { id: 'LF-00112', guest: 'Sophia Miller', room: '206', roomType: 'Standard', checkIn: 'Tomorrow', checkOut: '21 Jun', nights: 1, total: 210, status: 'Checked-out', source: 'Booking.com' },
  ],
} as const;
