import { useMemo, useState } from 'react';
import { Building2, CheckCircle2, Clock3, Compass, Globe2, Lightbulb, MapPin, WalletCards } from 'lucide-react';
import { currencyForCountry } from '@/utils/countryCurrency';

export type HotelInfoForm = { name: string; address: string; addressLine1: string; city: string; country: string; currency: string; timezone: string };
type Option = { value: string; label: string };

export default function HotelInfoPanel({ values, savedValues, currencyOptions, timezoneOptions, canEdit, saving, onChange, onSave, onReset, onOpenOperations }: { values: HotelInfoForm; savedValues: HotelInfoForm; currencyOptions: Option[]; timezoneOptions: Option[]; canEdit: boolean; saving: boolean; onChange: (next: HotelInfoForm) => void; onSave: () => Promise<void>; onReset: () => void; onOpenOperations: () => void }) {
  const [errors, setErrors] = useState<Partial<Record<keyof HotelInfoForm, string>>>({});
  const dirty = JSON.stringify(values) !== JSON.stringify(savedValues);
  const inferredCurrency = currencyForCountry(values.country);
  const currencyLabel = currencyOptions.find((option) => option.value === values.currency)?.label || values.currency;
  const profileComplete = Boolean(values.name.trim() && values.city.trim() && values.country.trim() && values.currency && values.timezone);
  const localTime = useMemo(() => {
    try { return new Intl.DateTimeFormat(undefined, { timeZone: values.timezone, dateStyle: 'medium', timeStyle: 'short' }).format(new Date()); }
    catch { return 'Timezone unavailable'; }
  }, [values.timezone]);
  const update = (key: keyof HotelInfoForm, value: string) => { setErrors((current) => ({ ...current, [key]: undefined })); onChange({ ...values, [key]: value }); };
  const validate = () => {
    const next: typeof errors = {};
    if (!values.name.trim()) next.name = 'Hotel name is required.';
    if (!values.city.trim()) next.city = 'City is required.';
    if (!values.country.trim()) next.country = 'Country is required.';
    if (!values.currency) next.currency = 'Currency is required.';
    if (!values.timezone) next.timezone = 'Timezone is required.';
    setErrors(next);
    return !Object.keys(next).length;
  };

  const field = (key: keyof HotelInfoForm, label: string, required = false, placeholder?: string) => <label><span className="label">{label}{required ? ' *' : ''}</span><input aria-invalid={Boolean(errors[key])} className="input h-10" value={values[key]} disabled={!canEdit} placeholder={placeholder} onChange={(event) => update(key, event.target.value)} />{errors[key] ? <span className="mt-1 block text-xs text-rose-700">{errors[key]}</span> : null}</label>;

  return <div className="space-y-4 pb-16">
    <header className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-primary-50 text-primary-700 ring-1 ring-primary-100"><Building2 className="h-6 w-6" /></span><div><h2 className="text-2xl font-bold tracking-tight text-text-main">Hotel Information</h2><p className="mt-1 text-sm text-text-muted">Manage your hotel profile, location, currency, timezone, and operational settings.</p></div></div><span className={`inline-flex w-fit items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-medium ${profileComplete ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : 'border-amber-200 bg-amber-50 text-amber-700'}`}><CheckCircle2 className="h-4 w-4" />{profileComplete ? 'Profile complete' : 'Profile needs attention'}</span></header>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Hotel summary">
      {([[Building2, 'Hotel', values.name || 'Not configured', 'Property profile'], [MapPin, 'Location', [values.city, values.country].filter(Boolean).join(', ') || 'Not configured', 'Operating region'], [WalletCards, 'Currency', values.currency || 'Not configured', currencyLabel], [Clock3, 'Timezone', values.timezone || 'Not configured', 'Local hotel time']] as const).map(([Icon, label, value, detail]) => <article key={label} className="rounded-2xl border border-border bg-card p-4 shadow-sm"><Icon className="h-5 w-5 text-primary-600" /><p className="mt-2 text-xs font-semibold text-text-muted">{label}</p><p className="mt-1 truncate text-base font-bold text-text-main">{value}</p><p className="truncate text-xs text-text-muted">{detail}</p></article>)}
    </section>

    <div className="grid gap-4 2xl:grid-cols-[minmax(0,1fr)_18rem]">
      <form className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm" onSubmit={async (event) => { event.preventDefault(); if (validate()) await onSave(); }}>
        <section className="p-5"><div className="flex items-center gap-2 text-primary-700"><Building2 className="h-4 w-4" /><h3 className="font-semibold">1. Basic Hotel Details</h3></div><div className="mt-4">{field('name', 'Hotel Name', true, 'Grand Palace Hotel')}</div></section>
        <section className="border-t border-border p-5"><div className="flex items-center gap-2 text-primary-700"><MapPin className="h-4 w-4" /><h3 className="font-semibold">2. Location Details</h3></div><div className="mt-4 grid gap-4 sm:grid-cols-2">{field('city', 'City', true, 'Johannesburg')}<label><span className="label">Country *</span><input aria-invalid={Boolean(errors.country)} className="input h-10" value={values.country} disabled={!canEdit} placeholder="South Africa" onChange={(event) => { const country = event.target.value; const currency = currencyForCountry(country); setErrors((current) => ({ ...current, country: undefined })); onChange({ ...values, country, currency: currency || values.currency }); }} />{errors.country ? <span className="mt-1 block text-xs text-rose-700">{errors.country}</span> : null}</label>{field('address', 'Mailing / full address (optional)', false, '123 Main Street, Downtown')}{field('addressLine1', 'Street / building (optional)', false, 'Block A, 5th Floor')}</div></section>
        <section className="border-t border-border p-5"><div className="flex items-center gap-2 text-primary-700"><Globe2 className="h-4 w-4" /><h3 className="font-semibold">3. Localisation</h3></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label><span className="label">Currency *</span><select aria-label="Currency *" aria-invalid={Boolean(errors.currency)} className="input h-10 disabled:cursor-not-allowed disabled:bg-bg" value={values.currency} disabled={!canEdit || Boolean(inferredCurrency)} onChange={(event) => update('currency', event.target.value)}>{currencyOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>{errors.currency ? <span className="mt-1 block text-xs text-rose-700">{errors.currency}</span> : null}<div className="mt-2 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-800">{inferredCurrency ? `Currency is automatically set from ${values.country}.` : 'Select the hotel operating currency.'} Existing monetary values are not converted automatically.</div></label><label><span className="label">Timezone *</span><select aria-label="Timezone *" aria-invalid={Boolean(errors.timezone)} className="input h-10" value={values.timezone} disabled={!canEdit} onChange={(event) => update('timezone', event.target.value)}>{timezoneOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>{errors.timezone ? <span className="mt-1 block text-xs text-rose-700">{errors.timezone}</span> : null}<div className="mt-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-800"><span className="font-semibold">Current local time</span><span className="mt-1 block">{localTime}</span></div></label></div></section>
        <div className="sticky bottom-3 z-20 flex flex-col gap-3 border-t border-border bg-card/95 p-4 backdrop-blur sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-text-muted">{canEdit ? dirty ? 'You have unsaved changes.' : 'All changes are saved to your hotel profile.' : 'You have read-only access.'}</p><div className="flex gap-2"><button type="button" className="btn-outline" disabled={!dirty || !canEdit} onClick={() => { setErrors({}); onReset(); }}>Reset changes</button><button type="submit" className="btn-primary" disabled={!dirty || !canEdit || saving}>{saving ? 'Saving...' : 'Save changes'}</button></div></div>
      </form>

      <aside className="space-y-4"><section className="rounded-2xl border border-border bg-card p-4 shadow-sm"><Compass className="h-5 w-5 text-primary-600" /><h3 className="mt-2 font-semibold text-text-main">Operational Forecast Signals</h3><p className="mt-2 text-sm text-text-muted">Weather and location signals are used by Operations Center for advisories, demand tracking, and task creation.</p><div className="mt-4 space-y-2">{['Weather advisories', 'Demand tracking', 'Task creation', 'Operations Center insights'].map((item) => <div key={item} className="flex items-center gap-2 text-sm text-text-muted"><Lightbulb className="h-4 w-4 text-primary-600" />{item}</div>)}</div><button type="button" className="btn-outline mt-4 w-full" onClick={onOpenOperations}>Open Operations Center</button></section><section className="rounded-2xl border border-border bg-card p-4 shadow-sm"><h3 className="font-semibold text-text-main">Localisation status</h3><div className="mt-3 space-y-3 text-sm"><div className="flex items-center justify-between gap-3"><span className="text-text-muted">Currency</span><span className="font-medium text-text-main">{values.currency}</span></div><div className="flex items-center justify-between gap-3"><span className="text-text-muted">Timezone</span><span className="truncate font-medium text-text-main">{values.timezone}</span></div><div className="flex items-center justify-between gap-3"><span className="text-text-muted">Forecast ready</span><span className="font-medium text-emerald-700">{values.city && values.country && values.timezone ? 'Yes' : 'No'}</span></div></div></section>{!canEdit ? <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">An administrator must update hotel information.</div> : null}</aside>
    </div>
  </div>;
}
