import { Department, TicketCategory, TicketPriority, TicketStatus } from '@prisma/client';
import type { WorkflowDefinition } from './workflowEngine.service.js';

export const workflowDefinitions: WorkflowDefinition[] = [
  {
    id: 'guest-check-in',
    name: 'Guest Check-in',
    description: 'Coordinates room readiness and front desk visibility after guest check-in.',
    enabled: true,
    trigger: { eventTypes: ['booking.checked_in'] },
    conditions: [{ type: 'ALWAYS' }],
    actions: [
      {
        type: 'PUBLISH_EVENT',
        eventType: 'workflow.timeline_event',
        payload: { summary: 'Guest check-in workflow started', severity: 'INFO' },
      },
      {
        type: 'AUDIT',
        action: 'WORKFLOW_GUEST_CHECK_IN',
        entity: 'booking',
        entityIdPath: 'bookingId',
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'guest-check-out',
    name: 'Guest Check-out',
    description: 'Guest Check-Out -> Housekeeping Task -> Room Inspection -> Room Available.',
    enabled: true,
    trigger: { eventTypes: ['booking.checked_out'] },
    conditions: [{ type: 'ALWAYS' }],
    actions: [
      {
        type: 'AUDIT',
        action: 'CHECKOUT_WORKFLOW_STARTED',
        entity: 'booking',
        entityIdPath: 'bookingId',
      },
      {
        type: 'UPDATE_ROOM_HOUSEKEEPING_STATUS',
        roomIdPath: 'roomId',
        status: 'DIRTY',
      },
      {
        type: 'CREATE_TASK',
        title: 'Clean and inspect room',
        description: 'Room requires cleaning after checkout.',
        department: Department.HOUSEKEEPING,
        category: TicketCategory.HOUSEKEEPING,
        priority: TicketPriority.MEDIUM,
        linkedEntityType: 'ROOM',
        linkedEntityIdPath: 'roomId',
        dueDate: 'SAME_DAY',
        sourceKey: 'checkout-cleaning:{{roomId}}:{{bookingId}}',
      },
      {
        type: 'NOTIFY_ROLES',
        roles: ['HOUSEKEEPING'],
        channels: ['DASHBOARD'],
        title: 'Room requires cleaning after checkout',
        body: '{{location}} requires cleaning after checkout.',
      },
      {
        type: 'AUDIT',
        action: 'HOUSEKEEPING_TASK_CREATED',
        entity: 'room',
        entityIdPath: 'roomId',
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'maintenance-fault',
    name: 'Maintenance Fault',
    description: 'Routes urgent maintenance faults to maintenance leadership.',
    enabled: true,
    trigger: { eventTypes: ['maintenance.fault_created'] },
    conditions: [{ type: 'PAYLOAD_IN', path: 'severity', values: ['URGENT', 'CRITICAL', 'HIGH'] }],
    actions: [
      {
        type: 'NOTIFY_ROLES',
        roles: ['ADMIN', 'MANAGER', 'MODULE:maintenance_center'],
        channels: ['DASHBOARD'],
        title: 'Urgent maintenance fault',
        body: '{{title}} requires attention.',
      },
      {
        type: 'PUBLISH_EVENT',
        eventType: 'maintenance.escalated',
        payload: { summary: 'Maintenance fault escalated', severity: 'WARNING' },
      },
    ],
    escalation: {
      delayMs: 30 * 60 * 1000,
      actions: [
        {
          type: 'NOTIFY_ROLES',
          roles: ['ADMIN', 'MANAGER'],
          channels: ['DASHBOARD'],
          title: 'Maintenance escalation pending',
          body: 'Urgent maintenance fault is still pending follow-up.',
        },
      ],
    },
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'security-alert',
    name: 'Security Alert',
    description: 'Alerts managers when Security Center records a security alert action.',
    enabled: true,
    trigger: { eventTypes: ['security.alert_acknowledged', 'security.alert_resolved'] },
    conditions: [{ type: 'ALWAYS' }],
    actions: [
      {
        type: 'AUDIT',
        action: 'WORKFLOW_SECURITY_ALERT_REVIEWED',
        entity: 'security_alert',
        entityIdPath: 'alertId',
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'smart-building-door-forced-open',
    name: 'Smart Building Door Forced Open',
    description: 'Creates a security response task when Smart Building reports a forced door.',
    enabled: true,
    trigger: { eventTypes: ['smart_building.alert_detected'] },
    conditions: [{ type: 'PAYLOAD_EQUALS', path: 'signal', value: 'DOOR_FORCED' }],
    actions: [
      {
        type: 'AUDIT',
        action: 'SMART_BUILDING_WORKFLOW_STARTED',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'CREATE_TASK',
        title: 'Investigate forced door event',
        description: '{{summary}}',
        department: Department.MANAGEMENT,
        category: TicketCategory.OTHER,
        priority: TicketPriority.URGENT,
        status: TicketStatus.OPEN,
        linkedEntityType: 'DOOR',
        linkedEntityIdPath: 'linkedEntityId',
        dueDate: 'SAME_DAY',
        sourceModule: 'SMART_BUILDING',
        duplicateKey: 'SMART_BUILDING:{{hotelId}}:{{deviceExternalId}}:DOOR_FORCED',
        duplicateWindowMinutes: 30,
        sourceKey: 'smart-building:{{eventId}}:door-forced',
      },
      {
        type: 'AUDIT',
        action: 'TASK_CREATED_FROM_SMART_BUILDING_EVENT',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'NOTIFY_ROLES',
        roles: ['ADMIN', 'MANAGER', 'MODULE:security_center'],
        channels: ['DASHBOARD'],
        title: 'Forced door event',
        body: '{{summary}}',
      },
      {
        type: 'AUDIT',
        action: 'NOTIFICATION_SENT_FROM_SMART_BUILDING_EVENT',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'PUBLISH_EVENT',
        eventType: 'security.door_forced_open',
        payload: { summary: 'Forced door event workflow triggered', severity: 'CRITICAL' },
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'smart-building-water-leak',
    name: 'Smart Building Water Leak',
    description: 'Creates a maintenance response task when a water leak sensor reports critical status.',
    enabled: true,
    trigger: { eventTypes: ['smart_building.alert_detected'] },
    conditions: [{ type: 'PAYLOAD_EQUALS', path: 'signal', value: 'WATER_LEAK' }],
    actions: [
      {
        type: 'AUDIT',
        action: 'SMART_BUILDING_WORKFLOW_STARTED',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'CREATE_TASK',
        title: 'Investigate water leak alert',
        description: '{{summary}}. Verify and isolate affected area.',
        department: Department.MAINTENANCE,
        category: TicketCategory.MAINTENANCE,
        priority: TicketPriority.URGENT,
        status: TicketStatus.OPEN,
        linkedEntityType: 'SENSOR_READING',
        linkedEntityIdPath: 'linkedEntityId',
        dueDate: 'SAME_DAY',
        sourceModule: 'SMART_BUILDING',
        duplicateKey: 'SMART_BUILDING:{{hotelId}}:{{deviceExternalId}}:WATER_LEAK',
        duplicateWindowMinutes: 30,
        sourceKey: 'smart-building:{{eventId}}:water-leak',
      },
      {
        type: 'AUDIT',
        action: 'TASK_CREATED_FROM_SMART_BUILDING_EVENT',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'NOTIFY_ROLES',
        roles: ['ADMIN', 'MANAGER', 'MODULE:maintenance_center'],
        channels: ['DASHBOARD'],
        title: 'Critical water leak detected',
        body: '{{summary}}',
      },
      {
        type: 'AUDIT',
        action: 'NOTIFICATION_SENT_FROM_SMART_BUILDING_EVENT',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'PUBLISH_EVENT',
        eventType: 'maintenance.water_leak_detected',
        payload: { summary: 'Water leak workflow triggered', severity: 'CRITICAL' },
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'smart-building-camera-offline',
    name: 'Smart Building Camera Offline',
    description: 'Creates a security/IT inspection task when a camera goes offline.',
    enabled: true,
    trigger: { eventTypes: ['smart_building.alert_detected'] },
    conditions: [{ type: 'PAYLOAD_EQUALS', path: 'signal', value: 'CAMERA_OFFLINE' }],
    actions: [
      {
        type: 'AUDIT',
        action: 'SMART_BUILDING_WORKFLOW_STARTED',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'CREATE_TASK',
        title: 'Inspect offline camera',
        description: '{{summary}}. Verify camera power, network, recorder, and vendor status.',
        department: Department.MANAGEMENT,
        category: TicketCategory.OTHER,
        priority: TicketPriority.HIGH,
        status: TicketStatus.OPEN,
        linkedEntityType: 'CAMERA',
        linkedEntityIdPath: 'linkedEntityId',
        dueDate: 'SAME_DAY',
        sourceModule: 'SMART_BUILDING',
        duplicateKey: 'SMART_BUILDING:{{hotelId}}:{{deviceExternalId}}:CAMERA_OFFLINE',
        duplicateWindowMinutes: 30,
        sourceKey: 'smart-building:{{eventId}}:camera-offline',
      },
      {
        type: 'AUDIT',
        action: 'TASK_CREATED_FROM_SMART_BUILDING_EVENT',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'NOTIFY_ROLES',
        roles: ['ADMIN', 'MANAGER', 'MODULE:security_center'],
        channels: ['DASHBOARD'],
        title: 'Camera offline',
        body: '{{summary}}',
      },
      {
        type: 'AUDIT',
        action: 'NOTIFICATION_SENT_FROM_SMART_BUILDING_EVENT',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'PUBLISH_EVENT',
        eventType: 'security.camera_offline',
        payload: { summary: 'Camera offline workflow triggered', severity: 'WARNING' },
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'smart-building-panic-button',
    name: 'Smart Building Panic Button',
    description: 'Creates a critical security task when a panic button is activated.',
    enabled: true,
    trigger: { eventTypes: ['smart_building.alert_detected'] },
    conditions: [{ type: 'PAYLOAD_EQUALS', path: 'signal', value: 'PANIC_BUTTON' }],
    actions: [
      {
        type: 'AUDIT',
        action: 'SMART_BUILDING_WORKFLOW_STARTED',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'CREATE_TASK',
        title: 'Respond to panic button',
        description: '{{summary}}',
        department: Department.MANAGEMENT,
        category: TicketCategory.OTHER,
        priority: TicketPriority.URGENT,
        status: TicketStatus.OPEN,
        linkedEntityType: 'SENSOR_READING',
        linkedEntityIdPath: 'linkedEntityId',
        dueDate: 'SAME_DAY',
        sourceModule: 'SMART_BUILDING',
        duplicateKey: 'SMART_BUILDING:{{hotelId}}:{{deviceExternalId}}:PANIC_BUTTON',
        duplicateWindowMinutes: 30,
        sourceKey: 'smart-building:{{eventId}}:panic-button',
      },
      {
        type: 'AUDIT',
        action: 'TASK_CREATED_FROM_SMART_BUILDING_EVENT',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'NOTIFY_ROLES',
        roles: ['ADMIN', 'MANAGER', 'MODULE:security_center'],
        channels: ['DASHBOARD'],
        title: 'Panic button activated',
        body: '{{summary}}',
      },
      {
        type: 'AUDIT',
        action: 'NOTIFICATION_SENT_FROM_SMART_BUILDING_EVENT',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'PUBLISH_EVENT',
        eventType: 'security.panic_button',
        payload: { summary: 'Panic button workflow triggered', severity: 'CRITICAL' },
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'smart-building-hvac-alert',
    name: 'Smart Building HVAC Alert',
    description: 'Creates a maintenance response task when HVAC equipment reports warning or critical status.',
    enabled: true,
    trigger: { eventTypes: ['smart_building.alert_detected'] },
    conditions: [{ type: 'PAYLOAD_EQUALS', path: 'signal', value: 'HVAC_ALERT' }],
    actions: [
      {
        type: 'AUDIT',
        action: 'SMART_BUILDING_WORKFLOW_STARTED',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'CREATE_TASK',
        title: 'Inspect HVAC alert',
        description: '{{summary}}. Check HVAC unit, controls, filters, and vendor system status.',
        department: Department.MAINTENANCE,
        category: TicketCategory.MAINTENANCE,
        priority: TicketPriority.HIGH,
        status: TicketStatus.OPEN,
        linkedEntityType: 'SMART_BUILDING_DEVICE',
        linkedEntityIdPath: 'linkedEntityId',
        dueDate: 'SAME_DAY',
        sourceModule: 'SMART_BUILDING',
        duplicateKey: 'SMART_BUILDING:{{hotelId}}:{{deviceExternalId}}:HVAC_ALERT',
        duplicateWindowMinutes: 30,
        sourceKey: 'smart-building:{{eventId}}:hvac-alert',
      },
      {
        type: 'AUDIT',
        action: 'TASK_CREATED_FROM_SMART_BUILDING_EVENT',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'NOTIFY_ROLES',
        roles: ['ADMIN', 'MANAGER', 'MODULE:maintenance_center'],
        channels: ['DASHBOARD'],
        title: 'HVAC alert detected',
        body: '{{summary}}',
      },
      {
        type: 'AUDIT',
        action: 'NOTIFICATION_SENT_FROM_SMART_BUILDING_EVENT',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'PUBLISH_EVENT',
        eventType: 'maintenance.hvac_alert_detected',
        payload: { summary: 'HVAC alert workflow triggered', severity: 'WARNING' },
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'smart-building-sensor-offline',
    name: 'Smart Building Sensor Offline',
    description: 'Creates a maintenance inspection task when a Smart Building sensor goes offline.',
    enabled: true,
    trigger: { eventTypes: ['smart_building.alert_detected'] },
    conditions: [{ type: 'PAYLOAD_EQUALS', path: 'signal', value: 'SENSOR_OFFLINE' }],
    actions: [
      {
        type: 'AUDIT',
        action: 'SMART_BUILDING_WORKFLOW_STARTED',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'CREATE_TASK',
        title: 'Inspect offline sensor',
        description: '{{summary}}. Check power, network, battery, and vendor gateway status.',
        department: Department.MAINTENANCE,
        category: TicketCategory.MAINTENANCE,
        priority: TicketPriority.HIGH,
        status: TicketStatus.OPEN,
        linkedEntityType: 'SMART_BUILDING_DEVICE',
        linkedEntityIdPath: 'linkedEntityId',
        dueDate: 'SAME_DAY',
        sourceModule: 'SMART_BUILDING',
        duplicateKey: 'SMART_BUILDING:{{hotelId}}:{{deviceExternalId}}:SENSOR_OFFLINE',
        duplicateWindowMinutes: 30,
        sourceKey: 'smart-building:{{eventId}}:sensor-offline',
      },
      {
        type: 'AUDIT',
        action: 'TASK_CREATED_FROM_SMART_BUILDING_EVENT',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'NOTIFY_ROLES',
        roles: ['ADMIN', 'MANAGER', 'MODULE:maintenance_center'],
        channels: ['DASHBOARD'],
        title: 'Smart Building sensor offline',
        body: '{{summary}}',
      },
      {
        type: 'AUDIT',
        action: 'NOTIFICATION_SENT_FROM_SMART_BUILDING_EVENT',
        entity: 'smart_building_event',
        entityIdPath: 'linkedEntityId',
      },
      {
        type: 'PUBLISH_EVENT',
        eventType: 'maintenance.sensor_offline',
        payload: { summary: 'Sensor offline workflow triggered', severity: 'WARNING' },
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'housekeeping-complete',
    name: 'Housekeeping Complete',
    description: 'Records room readiness once housekeeping marks a room clean.',
    enabled: true,
    trigger: { eventTypes: ['housekeeping.status_updated'] },
    conditions: [{ type: 'PAYLOAD_EQUALS', path: 'status', value: 'CLEAN' }],
    actions: [
      {
        type: 'PUBLISH_EVENT',
        eventType: 'room.ready_for_arrival',
        payload: { summary: 'Room marked clean and ready', severity: 'SUCCESS' },
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'reservation-cancelled',
    name: 'Reservation Cancelled',
    description: 'Publishes a revenue/operations signal when a reservation is cancelled.',
    enabled: true,
    trigger: { eventTypes: ['booking.cancelled'] },
    conditions: [{ type: 'ALWAYS' }],
    actions: [
      {
        type: 'PUBLISH_EVENT',
        eventType: 'operations.reservation_cancelled',
        payload: { summary: 'Reservation cancellation may affect occupancy forecast', severity: 'WARNING' },
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'payment-completed',
    name: 'Payment Completed',
    description: 'Records successful payment workflow completion.',
    enabled: true,
    trigger: { eventTypes: ['payment.completed', 'financial.payment_completed'] },
    conditions: [{ type: 'ALWAYS' }],
    actions: [
      {
        type: 'PUBLISH_EVENT',
        eventType: 'workflow.timeline_event',
        payload: { summary: 'Payment completed', severity: 'SUCCESS' },
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'vip-guest-arrival',
    name: 'VIP Guest Arrival',
    description: 'Notifies leadership and concierge for VIP arrivals.',
    enabled: true,
    trigger: { eventTypes: ['booking.checked_in', 'booking.created'] },
    conditions: [{ type: 'PAYLOAD_EQUALS', path: 'vip', value: true }],
    actions: [
      {
        type: 'CREATE_TASK',
        title: 'VIP guest arrival follow-up',
        description: 'Coordinate VIP welcome and guest preferences.',
        department: Department.CONCIERGE,
        category: TicketCategory.CONCIERGE,
        priority: TicketPriority.HIGH,
      },
      {
        type: 'NOTIFY_ROLES',
        roles: ['ADMIN', 'MANAGER'],
        channels: ['DASHBOARD'],
        title: 'VIP guest arrival',
        body: 'VIP guest workflow has started.',
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'operations-advisory',
    name: 'Operations Advisory',
    description: 'Tracks advisory-generated task workflow completion.',
    enabled: true,
    trigger: { eventTypes: ['task.created'] },
    conditions: [{ type: 'SOURCE_EQUALS', value: 'operations-center' }],
    actions: [
      {
        type: 'PUBLISH_EVENT',
        eventType: 'operations.advisory_workflow_started',
        payload: { summary: 'Operations advisory task created', severity: 'INFO' },
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'weather-alert',
    name: 'Weather Alert',
    description: 'Creates operations follow-up for critical weather events.',
    enabled: true,
    trigger: { eventTypes: ['weather.alert', 'operations.weather_alert'] },
    conditions: [{ type: 'PAYLOAD_IN', path: 'severity', values: ['WARNING', 'CRITICAL', 'HIGH'] }],
    actions: [
      {
        type: 'CREATE_TASK',
        title: 'Prepare for weather alert',
        description: '{{summary}}',
        department: Department.FRONT_DESK,
        category: TicketCategory.OTHER,
        priority: TicketPriority.HIGH,
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
  {
    id: 'ai-recommendation',
    name: 'AI Recommendation',
    description: 'Publishes AI recommendation workflow events for timeline and audit.',
    enabled: true,
    trigger: { eventTypes: ['ai.recommendation', 'operations.advisory_workflow_started'] },
    conditions: [{ type: 'ALWAYS' }],
    actions: [
      {
        type: 'PUBLISH_EVENT',
        eventType: 'workflow.timeline_event',
        payload: { summary: 'AI recommendation workflow processed', severity: 'INFO' },
      },
    ],
    completion: { eventType: 'workflow.completed', auditAction: 'WORKFLOW_COMPLETED' },
  },
];

export function getWorkflowDefinitions() {
  return workflowDefinitions.filter((workflow) => workflow.enabled);
}
